### ISSUE TITLE
JSON Format

### ISSUE THREAD

**Issue by reedacartwright** [CartwrightLab/coati#10]
I think we need more consistency between the JSON formats produced by `alignpair` and `sample`.

I think this should be our core alignment format:

```
{
  "aln": {
    "1": "CTCTGGATAGTG",
    "2": "CT----ATAGTG"
  },
  "score": 0.994785,
  "log_score": -0.00522821
}
```

With `sample` outputting an array of of these.

I chose to use `score` instead of `weight` here under the assumption that alignpair will get used more often than sample. But we should use the same name in both outputs even if they are slightly different.

**Comment by reedacartwright** [comment]
Or maybe we should just have a single "score" that the log-likelihood of the best alignment or the log-weight of a sampled alignment?

**Comment by reedacartwright** [comment]
Also, should we replace 'aln' with 'alignment'? Or keep it brief to save on file size?

**Comment by jgarciamesa** [comment]
> Or maybe we should just have a single "score" that the log-likelihood of the best alignment or the log-weight of a sampled alignment?

I think only having the log score makes sense. Either "score" or "log_score" works, depends if we want to be explicit that the score is in log space.

> Also, should we replace 'aln' with 'alignment'? Or keep it brief to save on file size?

'alignment' might be better, it's only a few extra characters.
