### ISSUE TITLE
msa example?

### ISSUE THREAD

**Issue by KarlFetter** [CartwrightLab/coati#23]
Hi, can you post an example for using the msa? I’m getting hung up on how to specify the reference sequence. I have the sequence in a file called ref.fa and I’m getting a `ERROR: Node ref.fa not found.` with this command: `coati msa -m mar-ecm -o global_tps global_tps.fa global_tps.tre ref.fa`

Thanks!

**Comment by reedacartwright** [comment]
@KarlFetter Instead of 'ref.fa', try including the reference sequence in global_tps.fa, and using the name of the sequence in global_tps.fa that you want to use as the reference.
