### ISSUE TITLE
Google Benchmark enabled by default.

### ISSUE THREAD

**Issue by reedacartwright** [CartwrightLab/coati#8]
Google is enabled by default. I think it should be disabled by default.

**Comment by jgarciamesa** [comment]
In meson, [`benchmark`](https://mesonbuild.com/Reference-manual_functions.html#benchmark) (identical behavior to `test`) doesn't have an option to not be build by default. There's an [open issue](https://github.com/mesonbuild/meson/issues/2518) about this in meson with an [open PR](https://github.com/mesonbuild/meson/pull/6511) as well.

For now I would add a [custom build option](https://mesonbuild.com/Build-options.html#build-options) to enable benchmarking, similar to how enabling coverage works. Disabled by default, to enable benchmarking users would run: `meson setup builddir -Dbenchmark=true`, then compile.

**Comment by reedacartwright** [comment]
Do you think we can use a build option to control whether the benchmark
subdir is included or not?

**Comment by reedacartwright** [comment]
Let's do the same thing for tests but have them default to being on.

**Comment by jgarciamesa** [comment]
PR #11 updated with a build option to enable/disable unit tests. Enabled by default.
